// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP_FubBS5oged_ru0EvRQCSFsAEteS5QE',
    appId: '1:797482089681:web:c365eb8a1a2bc4c85c59f0',
    messagingSenderId: '797482089681',
    projectId: 'grocery-app-e6d96',
    authDomain: 'grocery-app-e6d96.firebaseapp.com',
    storageBucket: 'grocery-app-e6d96.appspot.com',
    measurementId: 'G-TJ896ZDDLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUAQ3PPpu8R8E-cEPUs-ebHQZZdAB3grE',
    appId: '1:797482089681:android:7da0a2cbd0f76dbb5c59f0',
    messagingSenderId: '797482089681',
    projectId: 'grocery-app-e6d96',
    storageBucket: 'grocery-app-e6d96.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx2aDLcvfjsrGokf_hIFw7e2zB8NJZJ5g',
    appId: '1:797482089681:ios:055f36545cb76ae75c59f0',
    messagingSenderId: '797482089681',
    projectId: 'grocery-app-e6d96',
    storageBucket: 'grocery-app-e6d96.appspot.com',
    iosClientId: '797482089681-i8oqr3kpi83orfdgd6g49g3qc4s347nt.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx2aDLcvfjsrGokf_hIFw7e2zB8NJZJ5g',
    appId: '1:797482089681:ios:055f36545cb76ae75c59f0',
    messagingSenderId: '797482089681',
    projectId: 'grocery-app-e6d96',
    storageBucket: 'grocery-app-e6d96.appspot.com',
    iosClientId: '797482089681-i8oqr3kpi83orfdgd6g49g3qc4s347nt.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryApp',
  );
}
